### ISSUE TITLE
Could not move new index

### ISSUE THREAD

**Issue by concept-core** [malkusch/php-autoloader#8]
Hello I never have gotten this code before : 
```php
Fatal error: Uncaught exception 'malkusch\autoloader\AutoloaderException_Index_IO' with message 'Could not move new index C:\Users\concept-core.nl\AppData\Local\Temp\AutDBB6.tmp to C:\Users\CONCEP~1.NL\AppData\Local\Temp\malkusch\autoloader\AutoloaderIndex_SerializedHashtable_GZ052a1b4093c9c5f322de5c7a15bf4a6b: rename(C:\Users\concept-core.nl\AppData\Local\Temp\AutDBB6.tmp,C:\Users\CONCEP~1.NL\AppData\Local\Temp\malkusch\autoloader\AutoloaderIndex_SerializedHashtable_GZ052a1b4093c9c5f322de5c7a15bf4a6b): The system cannot find the path specified. (code: 3)' in C:\xampp\htdocs\wouter\concept_core_nl\vendor\malkusch\php-autoloader\Autoloader\index\AutoloaderIndex_File.php:304 Stack trace: #0 C:\xampp\htdocs\wouter\concept_core_nl\vendor\malkusch\php-autoloader\Autoloader\index\AutoloaderIndex.php(275): malkusch\autoloader\AutoloaderIndex_File->saveRaw() #1 C:\xampp\htdocs\wouter\concept_core_nl\vendor\malkusch\php-autoloader\Autoloader\index\AutoloaderIndex.php(316): malkusch\autoloader\AutoloaderIndex->save() #2 [internal f in C:\xampp\htdocs\wouter\concept_core_nl\vendor\malkusch\php-autoloader\Autoloader\index\AutoloaderIndex_File.php on line 304
```

What is this and how can I fix this ?

**Comment by malkusch** [comment]
> Could not move new index C:\Users\concept-core.nl\AppData\Local\Temp\AutDBB6.tmp to C:\Users\CONCEP~1.NL\AppData\Local\Temp\malkusch\autoloader\AutoloaderIndex_SerializedHashtable_GZ052a1b4093c9c5f322de5c7a15bf4a6b

I'd say that's the same as in #7. Update to Autoloader-1.14.6.

**Comment by concept-core** [comment]
Did you also update composer already ?
I got mine using composer.

**Comment by malkusch** [comment]
> Did you also update composer already?

yes

**Comment by concept-core** [comment]
:+1:
